language: node_js
node_js:
  - node

before_script:
  - npm install -g gulp-cli

script: gulp build

before_deploy: gulp deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master